version: "3.9"
services:
    contract-modification-service:
        container_name: contract-modification-service
        build: JenkinsDockerPractice\app\publish
        ports:
            - "5002:80"
